name: Build & Release Biblioteca

on:
  push:
    tags:
      - 'v*'   # corre cuando se sube un tag como v1.0, v2.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compilar ejecutable
        run: |
          pyinstaller --onefile --noconsole --name Biblioteca main.py

      - name: Renombrar binario
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/Biblioteca.exe Biblioteca-windows.exe
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            mv dist/Biblioteca Biblioteca-linux
          else
            mv dist/Biblioteca Biblioteca-macos
          fi

      - name: Subir binario como artifact
        uses: actions/upload-artifact@v3
        with:
          name: Biblioteca-${{ matrix.os }}
          path: Biblioteca-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Crear Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
